# druid config
spring:
  datasource:
    dynamic:
      druid:
        # 初始连接数
        initialSize: 10
        # 最小连接数
        minIdle: 10
        # 最大连接数
        maxActive: 30
        # 获取连接超时时间
        maxWait: 5000
        # maxOpenPreparedStatements: 100
        max-pool-prepared-statement-per-connection-size: 100
        # 连接有效性检测时间
        timeBetweenEvictionRunsMillis: 60000
        # 连接在池中最小生存的时间
        minEvictableIdleTimeMillis: 300000
        # 连接在池中最大生存的时间
        maxEvictableIdleTimeMillis: 900000
        # 检测连接是否有效
        validationQuery: 'SELECT 1'
        validationQueryTimeout: 3000
        # 指明连接是否被空闲连接回收器(如果有)进行检验.如果检测失败,则连接将被从池中去除
        testWhileIdle: true
        # 指明是否在从池中取出连接前进行检验,如果检验失败, 则从池中去除连接并尝试取出另一个
        testOnBorrow: false
        # 是否在归还到池中前进行检验
        testOnReturn: false
        keepAlive: true
        filters: 'stat,wall'
        connectionProperties:
          druid.stat.mergeSql: true
          druid.stat.slowSqlMillis: 5000
        # useGlobalDataSourceStat: false
    druid:
      webStatFilter:
        enabled: true
        urlPattern: '/*'
        exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*'
      statViewServlet:
        enabled: true
        resetEnable: false
        allow: '127.0.0.1'
        deny:
        urlPattern: '/druid/*'
        loginUsername: 'admin'
        loginPassword: '123456'
