#jwt
security:
  jwt:
    header: Authorization
    # 令牌前缀
    token-start-with: Bearer
    # 必须使用最少88位的Base64对该令牌进行编码
    base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
    # 令牌过期时间 此处单位/秒 ，默认4小时，可在此网站生成 https://www.convertworld.com/zh-hans/time/milliseconds.html
    token-validity-in-seconds: 14400
    # 在线用户key
    online-key: "online_key:"
    # token 续期检查时间范围（默认30分钟，单位毫秒），在token即将过期的一段时间内用户操作了，则给用户的token续期
    detect: 1800000
    # 续期时间范围，默认1小时，单位毫秒
    renew: 3600000
    #密码加密传输，前端公钥加密，后端私钥解密
    rsa-private-key: MIIBUwIBADANBgkqhkiG9w0BAQEFAASCAT0wggE5AgEAAkEAtLB/bcgI+oD/zq7g1ZzDWciAlygIeHv1KSruH1uOJHfn2OwB5oK/aUcdLm6l+ChD5tWAXxlTMn+k7tSnJUzCRwIDAQABAkBxPDbvpq+xxYwKi9/NHsvyBUxI7ka4sv5GCWhncGoZAZo0OC+HuqL8h/4V8gQawzOlG48zfuTLZG6M/wJMyWRpAiEA3W/Cg9cfk9OQT0CFbPRV/OzAcXnbywbLQZz+28Z6TWMCIQDQ5IzeUYtoID67cTxadpIt/h665Drhi6SrHb3Wt0cuzQIgBCYv8uB5CwAP2CxRU7VQVyjogjfSUn+SF2ylqeCSMhkCIC6sUjk+OQq74ahZ5aVExuaV1+HkKq/IVrORAqCd9L6lAiBAbkr/69o3etEo2Kj4kuv2u10y8Kv7EURsi6UM/wbJ4Q==

# DataSource Config
spring:
  # emqx 配置
  emqx:
    apikey: fb7daafb37d21221
    api-secret: iQyNSHSGMFg8juZL7qeUm0AuHaMJMjrEOE5B0Gixs9BB
    host: 192.168.2.201
    port: 18083
  # mqtt 配置
  mqtt:
    # 账号
    username: server-yunxiao-iot
    # 密码
    password: yunxiao@123
    # mqtt连接tcp地址
    host-url: tcp://192.168.2.201:1883
    # 客户端Id，不能相同，采用随机数 ${random.value}
    client-id: ${random.int}
    # 默认主题
    default-topic: test
    # 超时时间
    timeout: 30
    # 保持连接
    keepalive: 30
    # 清除会话(设置为false,断开连接，重连后使用原来的会话 保留订阅的主题，能接收离线期间的消息)
    clearSession: true
    # 秘钥(加密sha256)
    secret: ON7zjztEY7yOJQ1Y2RpyHkyXmWTNk6nkWCx
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          url: jdbc:mysql://192.168.2.201:3306/iotadmin_dev?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: yunxiao@123
        slave1:
          url: jdbc:mysql://192.168.2.201:3306/iotadmin_dev?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: yunxiao@123